[package]
name = "complementary_data_converter"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.9.2"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = { version = "1.0.83", features = ["preserve_order"] }
walkdir = "2.3.2"
